<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [69]:
import numpy as np

valores_aleatorios = np.random.randint(0,100,100)
valor_maximo = np.max(valores_aleatorios)
valor_minimo = np.min(valores_aleatorios)

print(valor_maximo,valor_minimo)

99 0


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [4]:
import numpy as np

def modulo_vetor(vetor):
    return np.linalg.norm(vetor)
vetor = np.array([3, 4])
modulo_vetor(vetor)  

5.0

In [3]:
vetor = np.array([3, 4])
modulo_vetor(vetor)

5.0

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [7]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

In [6]:
# Solução
def calculate_eqm(y_prediction, y_real):
    erro = y_prediction - y_real
    eqm = np.mean(erro**2)
    return eqm

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [8]:
def array_bidimensional(linhas, colunas):
    array = np.zeros((linhas, colunas))
    array[0,:] = 1
    array[-1,:] = 1
    array[:,0] = 1
    array[:,-1] = 1
    return array

In [9]:
array_bidimensional(5, 5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [5]:
import numpy as np

def adicionar_borda(array):
    borda = 1
    return np.pad(array, pad_width=borda, mode='constant', constant_values=0)

array = np.array([[1, 2, 3], [4, 5, 6]])
adicionar_borda(array)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [6]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [11]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
def process_EEG_signal(sinais_eeg):
    media = np.mean(sinais_eeg, axis=0)
    sinais_processados = sinais_eeg - media
    return sinais_processados

X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [12]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-519.6749858951293

In [13]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[-0.41901016,  1.09481119, -0.56429386, ..., -0.70331175,
        -0.73747496,  0.38332226],
       [-0.99929549,  1.3001228 ,  0.69423061, ..., -1.27020918,
         0.00450474, -0.89891242],
       [ 0.64812238,  1.38053353, -0.16230337, ...,  0.59557049,
        -0.23129206, -0.48139218],
       ...,
       [-0.49469976,  0.48600668,  1.31358149, ..., -0.2000844 ,
         1.74985513, -0.59065963],
       [ 1.36065391, -0.53023623,  0.93528511, ...,  0.06207668,
        -0.41179431, -0.85472014],
       [ 0.36151835, -0.91531342, -1.39389795, ...,  0.09294921,
        -0.18032044,  0.12013525]])

In [14]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[-0.488063  ,  0.99865749, -0.52313508, ..., -0.6536372 ,
        -0.85962667,  0.56756541],
       [-1.06834833,  1.2039691 ,  0.73538938, ..., -1.22053464,
        -0.11764697, -0.71466927],
       [ 0.57906954,  1.28437984, -0.1211446 , ...,  0.64524504,
        -0.35344377, -0.29714903],
       ...,
       [-0.5637526 ,  0.38985298,  1.35474026, ..., -0.15040986,
         1.62770342, -0.40641648],
       [ 1.29160107, -0.62638993,  0.97644389, ...,  0.11175123,
        -0.53394602, -0.67047699],
       [ 0.2924655 , -1.01146712, -1.35273917, ...,  0.14262376,
        -0.30247215,  0.3043784 ]])

In [ ]:
# Solução

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [71]:
# Geremos um conjunto de dados qualquer
X = np.random.rand(300,15)
X

array([[0.08040687, 0.71577822, 0.20849349, ..., 0.43023737, 0.74955358,
        0.08003306],
       [0.97412285, 0.89908969, 0.18075379, ..., 0.71913164, 0.39562904,
        0.41784232],
       [0.41689995, 0.95168589, 0.29364543, ..., 0.86274539, 0.07943468,
        0.32975748],
       ...,
       [0.18799694, 0.91405412, 0.28348114, ..., 0.43662569, 0.03054076,
        0.48531366],
       [0.13212141, 0.17724108, 0.79888131, ..., 0.61415139, 0.59957648,
        0.37027607],
       [0.5477358 , 0.51904909, 0.13812479, ..., 0.13925949, 0.73713729,
        0.11373072]])

In [19]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [20]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [21]:
outliers_count

13

In [22]:
outliers

array([-3.2610852 ,  3.20785165,  3.04139669,  3.93174974, -3.28122586,
       -3.69333665, -3.1285957 ,  3.54697648, -3.55644585,  2.93287841,
        3.47889684,  3.62286331, -2.93334387])

In [18]:
# Solução

def locate_outliers(dados):
    media = np.mean(dados, axis=0)
    desvio_padrao = np.std(dados, axis=0)
    outliers = np.zeros_like(dados, dtype=bool)
    for i in range(dados.shape[1]):
        coluna = dados[:, i]
        outliers[:, i] = (coluna < media[i] - 3 * desvio_padrao[i]) | (coluna > media[i] + 3 * desvio_padrao[i])
    quantidade_outliers = np.sum(outliers)
    valores_outliers = dados[outliers]
    return outliers, quantidade_outliers, valores_outliers

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [24]:
vetor = np.arange(1, 22, 2)
vetor

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [74]:
array= np.random.randint(0,10,10)

array

array([8, 6, 5, 9, 9, 5, 1, 8, 2, 4])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [75]:
def normalize_data(array):
    media = np.mean(array)
    desvio_padrao = np.std(array)
    return (array - media) / desvio_padrao

array= np.random.randint(0,10,10)

normalize_data(array)

array([ 1.18444612, -0.2090199 , -1.60248593,  0.48771311, -1.60248593,
        0.48771311,  1.18444612, -0.90575292,  0.1393466 ,  0.83607962])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [37]:
def estatisticas_turma(notas):
    media = np.mean(notas)
    desvio_padrao = np.std(notas)
    num_notas_maior_7 = np.sum(notas > 7.0)
    num_reprovacoes = np.sum(notas < 5.0)
    menor_nota = np.min(notas)
    maior_nota = np.max(notas)
    return np.array([media, desvio_padrao, num_notas_maior_7, num_reprovacoes, menor_nota, maior_nota])


notas = np.random.randint(0, 11, 100)

estatisticas_turma(notas)

array([ 5.01      ,  3.14482114, 26.        , 42.        ,  0.        ,
       10.        ])